export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
export const MINUS_PRODUCT_TO_CART = "MINUS_PRODUCT_TO_CART";
export const REMOVE_PRODUCT_TO_CART = "REMOVE_PRODUCT_TO_CART";
export const IS_SHOW_POPUP = "IS_SHOW_POPUP";
export const FETCH_DATA_PRODUCTS = "FETCH_DATA_PRODUCTS";
export const FETCH_DATA_PRODUCTS_FAIL = "FETCH_DATA_PRODUCTS_FAIL";
export const FETCH_DATA_PRODUCTS_SUCCESS = "FETCH_DATA_PRODUCTS_SUCCESS";